### ISSUE TITLE
VMS Mosaic 4.3?

### ISSUE THREAD

**Issue by roytam1** [ryanwoodsmall/vms-mosaic#1]
I wonder if you have version 4.3 of VMS Mosaic (MOSAIC4_3.ZIP)?
I had it in the past but I didn't keep the original one.

**Comment by ryanwoodsmall** [comment]
Apologies, unfortunately don't have that one. Last mention the VMS Mosaic page from the wayback machine is 4.2, not sure if 4.3 was ever widely disseminated and/or may have been limited to usenet:

- http://web.archive.org/web/20131117023556/http://vaxa.wvnet.edu/vmswww/vms_mosaic.html

Scouring wayback, bitsavers, etc. doesn't turn up anything that I can find re: 4.3, and digging through some old HP PDFs only shows reference to 3.x. And of course google has decided to bury ftp protocol links so that's out. The floodgap folks have a non-VMS fork of Mosaic 2.7b5 that's been updated to build on macOS, Linux, etc.:

- https://www.floodgap.com/retrotech/machten/mosaic/

The bitsavers list(s) might be a good next step, if anyone has that archive, it's probably someone there. Here's a discussion about 4.2:

- bitsavers discussion from 8/2018: http://bitsavers.org/mailing_lists/cctalk_mailing_list/2018-August.txt

Sorry! Wish I had a better answer. -r

**Comment by ryanwoodsmall** [comment]
Closing this - do leave a note if you find a copy though!

**Comment by roytam1** [comment]
My modified copy with changes for compiling in Linux (dated 2011) is here for reference: https://github.com/roytam1/vms-mosaic/commit/21a1fa1d96584b0763504b3ab967b4fda4fe7f22
